language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 3.0.0

before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec

deploy:
 provider: heroku
 api_key: YOUT_ACCOUNT_API_HERE
 app: YOUR_APP_NAME_HERE
 run: "rake db:migrate"
 on:
  all_branches: true
